name: Daily Web Scraper
on:
  schedule:
    - cron: '0 10 * * *'  # Runs daily at 3:30 PM IST
  workflow_dispatch:        # allows manual trigger
jobs:
  run-scraper:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install scrapy
    - name: Run scraping script
      run: python run_scrapy_job.py